# Installation d'environnements

* on utilise conda
    * on liste les dépendances d'un projet : `conda list -e > requirements.txt`
    * on les installe : `conda create --name <env> --file requirements.txt`
    
## Sans internet

* on utilise un ordinateur qui a internet
    * on installe les paquets nécessaires au projet 
    * solution 1 (pas terrible) : on peut copier le `site-packages` de l'environnement 
    * solution 2 (mieux) : https://thilinamad.medium.com/install-python-packages-via-pip-without-an-internet-connection-b3dee83b4c2d
        * la clé pour installer tous les paquets : 
            * `pip download -r requirements.txt C:\dossier\ou\on\veut`
            * `pip install --no-index --find-links=<local-folder> <package-name> `

# Fonctions

In [13]:
def f(x, debug=False):
    if debug:
        print("on debug")
    return 3*x + 2

In [7]:
f(3, True)
f(3, debug=True)
f(x=3, debug=True)

on debug


11

In [12]:
print(2, 3, 4, 5, sep="--")

2--3--4--5


In [14]:
lambda x: 3*x+2

<function __main__.<lambda>(x)>

In [17]:
ma_liste = [(3, "r"), (2, "x"), (1, 'a')]
sorted?

In [19]:
sorted(["z", "a"])

['a', 'z']

```
def my_sorted(iterable, key=None, reverse=False):
    for old_item, item in ...(iterable):
        if key(old_item) < key(item):
            swap
        else:
            pass 
```

In [40]:
import random 

ma_liste = [(3, "r"), (2, "x"), (1, 'a')]
def ma_fonction(item):
    # print(item)
    return random.random()

sorted(ma_liste, key=ma_fonction)

[(2, 'x'), (3, 'r'), (1, 'a')]

In [41]:
import random 

ma_liste = [(3, "r"), (2, "x"), (1, 'a')]
sorted(ma_liste, key=lambda x: x[1])

[(1, 'a'), (3, 'r'), (2, 'x')]

In [160]:
class Vehicule:
    def __init__(self):
        self.son = "vroum"
        self.etat = "arretée"

class Moteur:
    def __init__(self, cylindre):
        self.cylindre = cylindre
        
class Voiture(Vehicule): # Véhicule est la classe mère
    nombre_de_roues = 4 # variable de classe
    
    def __init__(self, couleur="blanc"):
        print("dans init", self, couleur)
        self.color = couleur
        moteur = Moteur(4) # composition
        self.moteur = moteur
        super().__init__()
    
    def demarrer(self):
        print("dans demarrer", self)
        self.etat = "roule"
    
    def repeindre(self, couleur):
        self.color = couleur

In [163]:
cabriolet = Voiture() # on définit un objet, une instance de voiture
mustang = Voiture(couleur="beige")
print(type(cabriolet))

print(mustang.moteur.cylindre)
mustang.moteur = Moteur(8)
print(mustang.moteur.cylindre)

dans init <__main__.Voiture object at 0x000002683E93E410> blanc
dans init <__main__.Voiture object at 0x000002683E3D8D60> beige
<class '__main__.Voiture'>
4
8


In [159]:
print(cabriolet)
cabriolet.demarrer()
print("")
print(mustang)
mustang.demarrer()

dans demarrer <__main__.Voiture object at 0x000002683E3D9210>

dans demarrer <__main__.Voiture object at 0x000002683E3DA560>


In [116]:
print(cabriolet.color)
cabriolet.color = "vert"
print(cabriolet.color)

blanc
vert


In [117]:
cabriolet.son = "VROUMMMM"
print(cabriolet.son)

print(mustang.son)

VROUMMMM
vroum


In [118]:
v = Voiture()
print(v.etat)
v.demarrer()
print(v.etat)

dans init <__main__.Voiture object at 0x000002683E25A2F0> blanc
arretée
dans demarrer <__main__.Voiture object at 0x000002683E25A2F0>
roule


In [119]:
Voiture.nombre_de_roues = 3
cabriolet.nombre_de_roues = 5

In [120]:
cabriolet.nombre_de_roues, mustang.nombre_de_roues

(5, 3)

In [121]:
isinstance(2, str)

False

In [123]:
isinstance(mustang, Voiture), isinstance(mustang, Vehicule)

(True, True)

In [144]:
class A:
    def __init__(self):
        print("dans init A")
    
    def methode_A(self):
        print("dans methode_A")
    
    def methode_B(self):
        print("dans methode_B de A")
        
class B(A):
    def __init__(self):
        print("dans init B")
        super().__init__()
        
    def methode_B(self):
        super().methode_B()
        print("dans methode_B")

In [142]:
a = A()

dans init A


In [143]:
b = B()
b.methode_B()
b.methode_A()

dans init A
dans init B
dans init A
dans methode_B
dans methode_A


# Copy

In [172]:
a = [1, 2, 3]
b = a

print(a, b)

a[0] = 22
print(a, b)
print(id(a), id(b))
print(id(a[0]), id(b[0]))

[1, 2, 3] [1, 2, 3]
[22, 2, 3] [22, 2, 3]
2646702238400 2646702238400
2646627648400 2646627648400


In [173]:
import copy

a = [1, 2, 3]
b = copy.copy(a)

print(a, b)

a[0] = 22
print(a, b)

print(id(a), id(b))
print(id(a[0]), id(b[0]))

[1, 2, 3] [1, 2, 3]
[22, 2, 3] [1, 2, 3]
2646748070144 2646748014976
2646627648400 2646627647728


In [187]:
import copy

a = [
    [1], [2], [3]
]
b = copy.deepcopy(a)

print(a, b)

a[0][0] = 22
print(a, b)

print(id(a), id(b))
print(id(a[0]), id(b[0]))

[[1], [2], [3]] [[1], [2], [3]]
[[22], [2], [3]] [[1], [2], [3]]
2646707790592 2646746567552
2646752164672 2646742774336


In [185]:
import numpy as np


def calcul():
    res = np.zeros((3, 3))
    res = sinus_cardinal([1, 2, 3], [1, 2, 3])
    return res

def sinus_cardinal(x, y):
    res = np.zeros((len(x), len(y)))
    for i in range(res.shape[0]):
        for j in range(res.shape[1]):
            res[i, j] = i + j
    return res

print(f())

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


In [189]:
a = "salut "
print(a, id(a))
a += "les copains"
print(a, id(a))

salut  2646752320304
salut les copains 2646680046928


In [193]:
"---".join(["salut", "les copains"])

'salut---les copains'

In [195]:
a = 1
b = 2
a, b = b, a 
print(a, b)

2 1


In [202]:
def f(value, a=[]):
    print(id(a))
    a.append(value)
    return a

def f2(value, a=None):
    if a is None:
        a = []
    print(id(a))
    a.append(value)
    return a

b = f2(5)
print(b)

c = f2(6)
print(b, c)

TypeError: f2() missing 1 required positional argument: 'a'

In [199]:
def f(a=print("toto")):
    print("dans a")

toto


In [208]:
ezfrtyukilikjy = None
print(id(ezfrtyukilikjy))

140729758539392


In [1]:
1 + "1"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [2]:
[i*i for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# Oscilloscope 

* https://github.com/sgoadhouse/oscope-scpi/tree/f838073b9d800f672c2ae2cf2282ed974d59b69f
* https://xdevs.com/doc/HP_Agilent_Keysight/Programmer%27s%20Guide%20for%20InfiniiVision%203000%20X-Series%20Oscilloscopes%20%28PDF%29%203000_series_prog_guide%20c20141023%20%5B1270%5D.pdf
* https://github.com/sgoadhouse/msox3000
* https://github.com/tektronix/Programmatic-Control-Examples
* https://github.com/tektronix/Programmatic-Control-Examples/blob/66cee6cb38501f6a06190cb973e1187d3634e24d/Examples/Oscilloscopes/TekSeriesScopes_HighSpeedDigitizers/src/ReadWfmExample

In [8]:
import numpy as np
import matplotlib.pyplot as plt

xs = np.linspace(-2*np.pi, 2*np.pi, 100)
ys = np.cos(xs)
plt.plot(xs, ys)

ModuleNotFoundError: No module named 'matplotlib'